name: learn-github-actions
on:
  push:
    tags:
      - "v*"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          files: |
            release.txt
